name: sefapolicy
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.2.2
  - cudatoolkit=11.3.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pytorch3d=0.7.0
  # - py-opencv=4.6.0
  - cffi=1.15.1
  - ipykernel=6.16
  - matplotlib=3.6.1
  - zarr=2.12.0
  - numcodecs=0.10.2
  - hydra-core=1.2.0
  - einops=0.4.1
  - tqdm=4.64.1
  - dill=0.3.5.1
  - scikit-video=1.1.11
  - scikit-image=0.19.3
  - gym=0.21.0
  - pymunk=6.2.1
  - wandb=0.13.3
  - threadpoolctl=3.1.0
  - shapely=1.8.4
  - cython=0.29.32
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - termcolor=2.0.1
  - psutil=5.9.2
  - click=8.0.4
  - boto3=1.24.96
  - accelerate=0.13.2
  - datasets=2.6.1
  - diffusers=0.11.1
  # - av=10.0.0
  - cmake=3.24.3
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625
  - llvm-openmp=14
  - pip:
    - opencv-python==4.6.0.66
    - av==10.0.0
    - numpy==1.23.3
    - numba==0.53.1
    - scipy==1.13.1
    - h5py==3.13.0
    - tensorboard==2.17.1
    - tensorboardx==2.6.2
    - imagecodecs==2022.9.26
    - huggingface_hub==0.25.0   
    - ray[default,tune]==2.2.0
    # requires mujoco py dependencies libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
    - free-mujoco-py==2.1.6
    - pygame==2.1.2
    - pybullet-svl==3.1.6.4
    - robosuite @ https://github.com/cheng-chi/robosuite/archive/277ab9588ad7a4f4b55cf75508b44aa67ec171f0.tar.gz
    - robomimic==0.2.0
    - pytorchvideo==0.1.5
    # pip package required for jpeg-xl
    - imagecodecs==2022.9.26
    - r3m @ https://github.com/facebookresearch/r3m/archive/b2334e726887fa0206962d7984c69c5fb09cceab.tar.gz
    - dm-control==1.0.9
    - clip
    - grpcio==1.51.1
    - pydantic<2
    - protobuf==3.20.3
    - git+https://github.com/Farama-Foundation/Metaworld.git@master#egg=metaworld
    - dowel==0.0.3
    - akro==0.0.8
    - tensorflow
    # - garage --no-deps
