name: adroit_hammer_img

task_name: hammer

mode: ${mode}
sefa_name: ${sefa_name}

image_shape: &image_shape [3, 84, 84]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    img:
        shape: [3, 84, 84]
        type: rgb
    agent_pos:
      shape: [24]
      type: low_dim
  action:
    shape: [26]

env_runner:
  _target_: sefa_policy.env_runner.adroit_runner.AdroitRunner
  eval_episodes: 20
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  task_name: hammer
  render_size: 84
  use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: sefa_policy.dataset.adroit_dataset.AdroitDataset
  zarr_path: data/adroit_hammer_expert.zarr_84
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
  mode: ${mode}
  sefa_name: ${sefa_name}
  task_name: ${task_name}
